language: ruby
rvm:
- 2.2.3
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database workshops_test;' -U postgres
addons:
  postgresql: '9.3'
env:
- DB=postgresql
deploy:
  provider: heroku
  api_key:
    secure: a4qyxtD1lFlXOROwxqVFfHpAxjs7VHap+EMdzwWVUycUsbeWVxhmXKARFkd/EXo7XVHTR+dcp3KXnqWiU21gZxxO3cuUSAuTlIYqTS6lDX7D1k8KkFtgUPBwrblW/CvMgPEnXeWp9SppH+YZJOrMn+jYjrtfaVQEvYh0jADul4Gqdfp9mu9Y6CfvZaz67C1I4H809lJOuAZdbebyT5bqpmkeASeNevc7xpiDBu/3UM8hEPX8AT1xcCXsBugz/yAXLvmWjyIY7GUhNcC97dRnFV6PZE2Ai4eovrAyZ8+Rozv19+2+9jpiGYIm59x2khoJkCFsXy4RubvEijkBMWOsFs3SP4gNZTq3yBdtGPc616e/ulQRISqHaINEDxZcPU7iEbLz8fs6338XfmYebnRAes0v4SDp2nsJx7eBZlulYCNq3T4qmXfcnTHlDX1jPda1Y0R130vSs0tKy7rPec13lPwZftIlQPnJF00nhle9CtdGu0Z2r0OMVFwBBJYI2ZcswzdKYlsQ3wUhFtnIQw1O6+2RRqN5JNgn0GN4rOjKa54cGnnhMVGK+SMfT3zVHpzF1UYbtjlBy5+7tZedHoc225fRjlJzTRJOobVZaqHL/uUiljPXT02W7kx7BUgIejTrNuAyd5+ZwYvEkjgCJqWSlyylUkIpcjzggXBt6efCY+g=
  app: wroclaw-ror-workshops-2015
  on:
    repo: sztosz/wroclaw-ror-workshops-2015-december
