language: ruby
rvm:
  - 2.2.3
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database workshops_test;' -U postgres
addons:
  postgresql: '9.3'
env:
  - DB=postgresql