postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: workshops_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

test:
  <<: *defaults
